### ISSUE TITLE
cant open doors 

### ISSUE THREAD

**Issue by Tirus89** [mixMugz/msfs_tbm930_project#13]
lock our unlock I cant open the doors 
any of them

**Comment by mixMugz** [comment]
Check your mod. Something cause conflict

**Comment by twodogzz** [comment]
> 
> 
> lock our unlock I cant open the doors
> any of them

Hi @Tirus89,
I have the same door issue, as well as the pilot and copilot not disappearing when viewed from their positions or when I change the weights to below 100 lbs.
To resolve this I changed the mods folder name to "zz-aircraft-tbm930-improvement" so it loads into MSFS 2020 as the last mod.
Of course, this may make other mods in the community folder stop working correctly too.
So, @mixMugz is right ti identify that the issue is a conflict with another mod.

**Comment by mixMugz** [comment]
Conflict with another mod
