### ISSUE TITLE
Hi Mugz- Are you working on keeping this Mod up to date with the latest update? We haven't heard a word from you.

### ISSUE THREAD

**Issue by mahensley** [mixMugz/msfs_tbm930_project#36]

**Comment by rene-s** [comment]
Yeah OK that's a good question on one hand but on the other hand this project *is* MIT-licenced FOSS. Nothing is stopping us from fixing it ourselves (or pay someone to do it for us) and then providing a PR. Well, nothing except incompetence, that's why I did not attempt a fix yet. If someone actually has a clue about where to even look regarding #35 I'd gladly to so.

**Comment by mixMugz** [comment]
Updated
